
package com.escuela.digital.curso.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CursoService", targetNamespace = "http://service.curso.digital.escuela.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CursoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.escuela.digital.curso.service.Curso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearCurso", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.CrearCurso")
    @ResponseWrapper(localName = "crearCursoResponse", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.CrearCursoResponse")
    public Curso crearCurso(
        @WebParam(name = "arg0", targetNamespace = "")
        Curso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.escuela.digital.curso.service.Curso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificaCurso", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.ModificaCurso")
    @ResponseWrapper(localName = "modificaCursoResponse", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.ModificaCursoResponse")
    public Curso modificaCurso(
        @WebParam(name = "arg0", targetNamespace = "")
        Curso arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.escuela.digital.curso.service.Curso>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCursos", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.ObtenerCursos")
    @ResponseWrapper(localName = "obtenerCursosResponse", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.ObtenerCursosResponse")
    public List<Curso> obtenerCursos();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.escuela.digital.curso.service.Curso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminaCurso", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.EliminaCurso")
    @ResponseWrapper(localName = "eliminaCursoResponse", targetNamespace = "http://service.curso.digital.escuela.com/", className = "com.escuela.digital.curso.service.EliminaCursoResponse")
    public Curso eliminaCurso(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
