
package com.escuela.digital.curso.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CursoServiceImplService", targetNamespace = "http://service.curso.digital.escuela.com/", wsdlLocation = "http://polar-forest-03988.herokuapp.com/CursoService?wsdl")
public class CursoServiceImplService
    extends Service
{

    private final static URL CURSOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURSOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CURSOSERVICEIMPLSERVICE_QNAME = new QName("http://service.curso.digital.escuela.com/", "CursoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://polar-forest-03988.herokuapp.com/CursoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURSOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CURSOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CursoServiceImplService() {
        super(__getWsdlLocation(), CURSOSERVICEIMPLSERVICE_QNAME);
    }

    public CursoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURSOSERVICEIMPLSERVICE_QNAME, features);
    }

    public CursoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CURSOSERVICEIMPLSERVICE_QNAME);
    }

    public CursoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURSOSERVICEIMPLSERVICE_QNAME, features);
    }

    public CursoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CursoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CursoService
     */
    @WebEndpoint(name = "CursoServiceImplPort")
    public CursoService getCursoServiceImplPort() {
        return super.getPort(new QName("http://service.curso.digital.escuela.com/", "CursoServiceImplPort"), CursoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CursoService
     */
    @WebEndpoint(name = "CursoServiceImplPort")
    public CursoService getCursoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.curso.digital.escuela.com/", "CursoServiceImplPort"), CursoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURSOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CURSOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CURSOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
